"""add_cascade_delete_to_messages_project_fk

Revision ID: 2131e43c0dda
Revises: 8313cc334848
Create Date: 2026-07-03 12:41:48.929350

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "2131e43c0dda"
down_revision: Union[str, Sequence[str], None] = "8313cc334848"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("messages_project_id_fkey"), "messages", type_="foreignkey")
    op.create_foreign_key(
        None, "messages", "projects", ["project_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.create_foreign_key(
        op.f("messages_project_id_fkey"), "messages", "projects", ["project_id"], ["id"]
    )
    # ### end Alembic commands ###
