"""remove redundant admin_id from projects, source of truth is project_membership

Revision ID: 2a30004e7e71
Revises: 85ff86a72b0f
Create Date: 2026-07-02 21:53:20.477358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a30004e7e71'
down_revision: Union[str, Sequence[str], None] = '85ff86a72b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by'], ['id'])
    op.drop_constraint(op.f('projects_admin_id_fkey'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('admin_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('projects_admin_id_fkey'), 'projects', 'users', ['admin_id'], ['id'])
    op.drop_constraint(None, 'documents', type_='foreignkey')
    # ### end Alembic commands ###
