"""add size_bytes to documents and maintain project counters

Revision ID: 8313cc334848
Revises: 662d65361970
Create Date: 2026-07-03 08:53:58.717661

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8313cc334848"
down_revision: Union[str, Sequence[str], None] = "662d65361970"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add nullable first so existing rows don't violate the NOT NULL constraint,
    # backfill to 0, then tighten the constraint.
    op.add_column("documents", sa.Column("size_bytes", sa.BigInteger(), nullable=True))
    op.execute("UPDATE documents SET size_bytes = 0")
    op.alter_column("documents", "size_bytes", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "size_bytes")
    # ### end Alembic commands ###
