"""add fk documents project_id cascade

Revision ID: a71286368b57
Revises: 8a081528d38d
Create Date: 2026-06-27 16:54:29.975788

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a71286368b57"
down_revision: Union[str, Sequence[str], None] = "8a081528d38d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_documents_project_id",
        "documents",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_documents_project_id", "documents", type_="foreignkey")
    # ### end Alembic commands ###
